### ISSUE TITLE
Active Job crashed

### ISSUE THREAD

**Issue by DolezalDavid** [brandonhilkert/sucker_punch#233]
Hi,
can somebody help me please? 

I install sucker_punch as gem and use it with active job and sometime I don't receive notification.
Here is log
![obrazek](https://user-images.githubusercontent.com/52913270/99698554-36073a80-2a91-11eb-8e0e-3cc281922641.png)

My setup 
```
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x64-mingw32]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::SuckerPunchAdapter
  Mailer delivery                smtp
SCM:
  Filesystem                     
Redmine plugins:
  redmine_custom_workflows       1.0.3
  redmine_lightbox2              0.5.0
```

My config\configuration.yml:
```
# specific configuration options for production environment
# that overrides the default ones
production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: "<smtp_server_via_DNS_name>"
      port: 25
      domain: '<domain>'
      authentication: :login
      user_name: '<user>'
      password: '<pass>' 
      openssl_verify_mode: 'none'
```

I spent with it 2 days and nothing... :-(
